/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.94
 * Generated at: 2025-07-24 19:55:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.info;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.wso2.carbon.registry.info.ui.clients.InfoServiceClient;
import org.wso2.carbon.utils.ServerConstants;
import org.wso2.carbon.ui.CarbonUIMessage;
import org.wso2.carbon.registry.common.beans.RatingBean;

public final class rating_002dajaxprocessor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/tlds/carbontags.tld", Long.valueOf(1741069184000L));
    _jspx_dependants.put("/WEB-INF/tlds/fmt.tld", Long.valueOf(1741069184000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("org.wso2.carbon.registry.common.beans.RatingBean");
    _jspx_imports_classes.add("org.wso2.carbon.ui.CarbonUIMessage");
    _jspx_imports_classes.add("org.wso2.carbon.utils.ServerConstants");
    _jspx_imports_classes.add("org.wso2.carbon.registry.info.ui.clients.InfoServiceClient");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcarbon_005fjsi18n_0026_005fresourceBundle_005frequest_005fnamespace_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fbundle_0026_005fbasename;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fcarbon_005fjsi18n_0026_005fresourceBundle_005frequest_005fnamespace_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fbundle_0026_005fbasename = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fcarbon_005fjsi18n_0026_005fresourceBundle_005frequest_005fnamespace_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fbundle_0026_005fbasename.release();
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      //  carbon:jsi18n
      org.wso2.carbon.ui.taglibs.JSi18n _jspx_th_carbon_005fjsi18n_005f0 = (org.wso2.carbon.ui.taglibs.JSi18n) _005fjspx_005ftagPool_005fcarbon_005fjsi18n_0026_005fresourceBundle_005frequest_005fnamespace_005fnobody.get(org.wso2.carbon.ui.taglibs.JSi18n.class);
      boolean _jspx_th_carbon_005fjsi18n_005f0_reused = false;
      try {
        _jspx_th_carbon_005fjsi18n_005f0.setPageContext(_jspx_page_context);
        _jspx_th_carbon_005fjsi18n_005f0.setParent(null);
        // /info/rating-ajaxprocessor.jsp(27,0) name = resourceBundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_carbon_005fjsi18n_005f0.setResourceBundle("org.wso2.carbon.registry.info.ui.i18n.JSResources");
        // /info/rating-ajaxprocessor.jsp(27,0) name = request type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_carbon_005fjsi18n_005f0.setRequest(request);
        // /info/rating-ajaxprocessor.jsp(27,0) name = namespace type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_carbon_005fjsi18n_005f0.setNamespace("org.wso2.carbon.registry.info.ui");
        int _jspx_eval_carbon_005fjsi18n_005f0 = _jspx_th_carbon_005fjsi18n_005f0.doStartTag();
        if (_jspx_th_carbon_005fjsi18n_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fcarbon_005fjsi18n_0026_005fresourceBundle_005frequest_005fnamespace_005fnobody.reuse(_jspx_th_carbon_005fjsi18n_005f0);
        _jspx_th_carbon_005fjsi18n_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_carbon_005fjsi18n_005f0, _jsp_getInstanceManager(), _jspx_th_carbon_005fjsi18n_005f0_reused);
      }
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"../info/js/info.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../ajax/js/prototype.js\"></script>\n");
      out.write("\n");

    RatingBean ratingBean;
    String cookie = (String) session.getAttribute(ServerConstants.ADMIN_SERVICE_COOKIE);
    try{
        InfoServiceClient client = null;
        if (request.getParameter("rating") != null) {
            client = new InfoServiceClient(cookie, config, session);
            client.rateResource(request);
        } else {
            client = new InfoServiceClient(cookie, config, session);
        }
        ratingBean = client.getRatings(request);
    } catch (Exception e){
        response.setStatus(500);
        
      out.print(e.getMessage());
      out.write("\n");
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../admin/error.jsp?<%=e.getMessage()%>", out, false);
      out.write('\n');

        return;
    }
    float averageRating = ratingBean.getAverageRating();

    String[] userStars = ratingBean.getUserStars();
    String[] averageStars = ratingBean.getAverageStars();

      out.write('\n');
      //  fmt:bundle
      org.apache.taglibs.standard.tag.rt.fmt.BundleTag _jspx_th_fmt_005fbundle_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.BundleTag) _005fjspx_005ftagPool_005ffmt_005fbundle_0026_005fbasename.get(org.apache.taglibs.standard.tag.rt.fmt.BundleTag.class);
      boolean _jspx_th_fmt_005fbundle_005f0_reused = false;
      try {
        _jspx_th_fmt_005fbundle_005f0.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fbundle_005f0.setParent(null);
        // /info/rating-ajaxprocessor.jsp(57,0) name = basename type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fbundle_005f0.setBasename("org.wso2.carbon.registry.info.ui.i18n.Resources");
        int _jspx_eval_fmt_005fbundle_005f0 = _jspx_th_fmt_005fbundle_005f0.doStartTag();
        if (_jspx_eval_fmt_005fbundle_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_fmt_005fbundle_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_fmt_005fbundle_005f0);
          }
          do {
            out.write("\n");
            out.write("\n");
            out.write("    <table cellspacing=\"10\" border=\"0\">\n");
            out.write("        ");

            if (ratingBean.isLoggedIn()) {
                if (ratingBean.isVersionView()) {
        
            out.write("\n");
            out.write("\n");
            out.write("        <tr>\n");
            out.write("            <th valign=\"top\">");
            if (_jspx_meth_fmt_005fmessage_005f0(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
              return;
            out.write(":</th>\n");
            out.write("            <td nowrap=\"nowrap\">\n");
            out.write("                <div style=\"width:120px;\">\n");
            out.write("                    <img class=\"registryWriteOperation\" src=\"../resources/images/spacer.gif\" style=\"width:16px\"/>\n");
            out.write("                    <img class=\"registryNonWriteOperation\" src=\"../resources/images/spacer.gif\" style=\"width:16px\"/>\n");
            out.write("                    <img class=\"registryWriteOperation\" src=\"../info/images/r");
            out.print(userStars[0]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryNonWriteOperation\" src=\"../info/images/r");
            out.print(userStars[0]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryWriteOperation\" src=\"../info/images/r");
            out.print(userStars[1]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryNonWriteOperation\" src=\"../info/images/r");
            out.print(userStars[1]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryWriteOperation\" src=\"../info/images/r");
            out.print(userStars[2]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryNonWriteOperation\" src=\"../info/images/r");
            out.print(userStars[2]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryWriteOperation\" src=\"../info/images/r");
            out.print(userStars[3]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryNonWriteOperation\" src=\"../info/images/r");
            out.print(userStars[3]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryWriteOperation\" src=\"../info/images/r");
            out.print(userStars[4]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryNonWriteOperation\" src=\"../info/images/r");
            out.print(userStars[4]);
            out.write(".gif\"/>\n");
            out.write("                    <br/>\n");
            out.write("\n");
            out.write("                </div>\n");
            out.write("            </td>\n");
            out.write("            <th></th>\n");
            out.write("            <td></td>\n");
            out.write("        </tr>\n");
            out.write("\n");
            out.write("        ");

        } else {
        
            out.write("\n");
            out.write("        <tr>\n");
            out.write("            <th valign=\"top\">");
            if (_jspx_meth_fmt_005fmessage_005f1(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
              return;
            out.write(":</th>\n");
            out.write("            <td nowrap=\"nowrap\">\n");
            out.write("                <div id=\"ratingDivUser\" style=\"width:120px;\">\n");
            out.write("                    <span initialState=\"");
            out.print(userStars[0]);
            out.write(' ');
            out.print(userStars[1]);
            out.write(' ');
            out.print(userStars[2]);
            out.write(' ');
            out.print(userStars[3]);
            out.write(' ');
            out.print(userStars[4]);
            out.write("\"/>\n");
            out.write("                    <img class=\"registryWriteOperation\"\n");
            out.write("                         src=\"../resources/images/spacer.gif\" style=\"width:16px\"\n");
            out.write("                         onclick=\"setRating('");
            out.print(ratingBean.getPathWithVersion());
            out.write("', 0)\"\n");
            out.write("                         onmouseover=\"previewRating('ratingDivUser', 0)\"\n");
            out.write("                         onmouseout=\"clearPreview('ratingDivUser')\"/>\n");
            out.write("                    <img class=\"registryNonWriteOperation\"\n");
            out.write("                         src=\"../resources/images/spacer.gif\" style=\"width:16px\" />\n");
            out.write("                    <img class=\"registryWriteOperation\"\n");
            out.write("                         src=\"../info/images/r");
            out.print(userStars[0]);
            out.write(".gif\"\n");
            out.write("                         onclick=\"setRating('");
            out.print(ratingBean.getPathWithVersion());
            out.write("', 1)\"\n");
            out.write("                         onmouseover=\"previewRating('ratingDivUser', 1)\"\n");
            out.write("                         onmouseout=\"clearPreview('ratingDivUser')\"/>\n");
            out.write("                    <img class=\"registryNonWriteOperation\"\n");
            out.write("                         src=\"../info/images/r");
            out.print(userStars[0]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryWriteOperation\"\n");
            out.write("                         src=\"../info/images/r");
            out.print(userStars[1]);
            out.write(".gif\"\n");
            out.write("                         onclick=\"setRating('");
            out.print(ratingBean.getPathWithVersion());
            out.write("', 2)\"\n");
            out.write("                         onmouseover=\"previewRating('ratingDivUser', 2)\"\n");
            out.write("                         onmouseout=\"clearPreview('ratingDivUser')\"/>\n");
            out.write("                    <img class=\"registryNonWriteOperation\"\n");
            out.write("                         src=\"../info/images/r");
            out.print(userStars[1]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryWriteOperation\"\n");
            out.write("                         src=\"../info/images/r");
            out.print(userStars[2]);
            out.write(".gif\"\n");
            out.write("                         onclick=\"setRating('");
            out.print(ratingBean.getPathWithVersion());
            out.write("', 3)\"\n");
            out.write("                         onmouseover=\"previewRating('ratingDivUser', 3)\"\n");
            out.write("                         onmouseout=\"clearPreview('ratingDivUser')\"/>\n");
            out.write("                    <img class=\"registryNonWriteOperation\"\n");
            out.write("                         src=\"../info/images/r");
            out.print(userStars[2]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryWriteOperation\"\n");
            out.write("                         src=\"../info/images/r");
            out.print(userStars[3]);
            out.write(".gif\"\n");
            out.write("                         onclick=\"setRating('");
            out.print(ratingBean.getPathWithVersion());
            out.write("', 4)\"\n");
            out.write("                         onmouseover=\"previewRating('ratingDivUser', 4)\"\n");
            out.write("                         onmouseout=\"clearPreview('ratingDivUser')\"/>\n");
            out.write("                    <img class=\"registryNonWriteOperation\"\n");
            out.write("                         src=\"../info/images/r");
            out.print(userStars[3]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryWriteOperation\"\n");
            out.write("                         src=\"../info/images/r");
            out.print(userStars[4]);
            out.write(".gif\"\n");
            out.write("                         onclick=\"setRating('");
            out.print(ratingBean.getPathWithVersion());
            out.write("', 5)\"\n");
            out.write("                         onmouseover=\"previewRating('ratingDivUser', 5)\"\n");
            out.write("                         onmouseout=\"clearPreview('ratingDivUser')\"/>\n");
            out.write("                    <img class=\"registryNonWriteOperation\"\n");
            out.write("                         src=\"../info/images/r");
            out.print(userStars[4]);
            out.write(".gif\"/>\n");
            out.write("                </div>\n");
            out.write("            </td>\n");
            out.write("            <th></th>\n");
            out.write("            <td></td>\n");
            out.write("        </tr>\n");
            out.write("        ");
 }
        } 
            out.write("\n");
            out.write("        <tr>\n");
            out.write("            <th valign=\"top\">");
            if (_jspx_meth_fmt_005fmessage_005f2(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
              return;
            out.write(":</th>\n");
            out.write("            <td nowrap=\"nowrap\">\n");
            out.write("                <div id=\"ratingDivAvg\" style=\"width:120px;\">\n");
            out.write("                    <img class=\"registryWriteOperation\" src=\"../resources/images/spacer.gif\" style=\"width:16px\"/>\n");
            out.write("                    <img class=\"registryNonWriteOperation\" src=\"../resources/images/spacer.gif\" style=\"width:16px\"/>\n");
            out.write("                    <img class=\"registryWriteOperation\" src=\"../info/images/r");
            out.print(averageStars[0]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryNonWriteOperation\" src=\"../info/images/r");
            out.print(averageStars[0]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryWriteOperation\" src=\"../info/images/r");
            out.print(averageStars[1]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryNonWriteOperation\" src=\"../info/images/r");
            out.print(averageStars[1]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryWriteOperation\" src=\"../info/images/r");
            out.print(averageStars[2]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryNonWriteOperation\" src=\"../info/images/r");
            out.print(averageStars[2]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryWriteOperation\" src=\"../info/images/r");
            out.print(averageStars[3]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryNonWriteOperation\" src=\"../info/images/r");
            out.print(averageStars[3]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryWriteOperation\" src=\"../info/images/r");
            out.print(averageStars[4]);
            out.write(".gif\"/>\n");
            out.write("                    <img class=\"registryNonWriteOperation\" src=\"../info/images/r");
            out.print(averageStars[4]);
            out.write(".gif\"/>\n");
            out.write("                    <br/>\n");
            out.write("\n");
            out.write("                </div>\n");
            out.write("            </td>\n");
            out.write("            <td>(");
            out.print(averageRating);
            out.write(")</td>\n");
            out.write("            <td></td>\n");
            out.write("        </tr>\n");
            out.write("    </table>\n");
            int evalDoAfterBody = _jspx_th_fmt_005fbundle_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_fmt_005fbundle_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_fmt_005fbundle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fbundle_0026_005fbasename.reuse(_jspx_th_fmt_005fbundle_005f0);
        _jspx_th_fmt_005fbundle_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fbundle_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fbundle_005f0_reused);
      }
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f0_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
      // /info/rating-ajaxprocessor.jsp(66,29) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f0.setKey("my.rating");
      int _jspx_eval_fmt_005fmessage_005f0 = _jspx_th_fmt_005fmessage_005f0.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
      _jspx_th_fmt_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f1_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
      // /info/rating-ajaxprocessor.jsp(93,29) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f1.setKey("my.rating");
      int _jspx_eval_fmt_005fmessage_005f1 = _jspx_th_fmt_005fmessage_005f1.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f1);
      _jspx_th_fmt_005fmessage_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f2_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f2.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
      // /info/rating-ajaxprocessor.jsp(147,29) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f2.setKey("rating");
      int _jspx_eval_fmt_005fmessage_005f2 = _jspx_th_fmt_005fmessage_005f2.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f2);
      _jspx_th_fmt_005fmessage_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f2, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f2_reused);
    }
    return false;
  }
}
